# Generated by Django 5.2.9 on 2026-01-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_property_description_en_property_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydocument',
            old_name='document',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='house_app.property'),
        ),
    ]
